### ISSUE TITLE
Please push this image to docker hub

### ISSUE THREAD

**Issue by jar349** [GELOG/docker-ubuntu-hbase#8]
I just realized that this image isn't available in the gelog group of docker hub: https://hub.docker.com/u/gelog/.  That is both sad and fixable. :-)

**Comment by davidonlaptop** [comment]
Building: https://hub.docker.com/r/gelog/hbase/builds/

**Comment by jar349** [comment]
the build failed :(

**Comment by davidonlaptop** [comment]
hum, Apache removed the 1.2.3 archive. I'll try to upgrade to 1.2.4

**Comment by mikefaille** [comment]
@davidonlaptop You can use archive site for statics urls : https://archive.apache.org/dist/hbase/ :eyeglasses:

**Comment by mikefaille** [comment]
But, +1 for Hbase 1.2.4 :+1: 
https://archive.apache.org/dist/hbase/1.2.4/1.2.3_1.2.4RC1_compat_report.html

**Comment by davidonlaptop** [comment]
Pushed and building.

Good idea @mikefaille !

**Comment by jar349** [comment]
Sorry, I forgot to mention that I also had to update this to 1.2.4 to get
it to work.  :(

**Comment by davidonlaptop** [comment]
yep, I've bumped the version too. Let's see if the build succeeds.

**Comment by mikefaille** [comment]
@davidonlaptop  Ho crap our friend @jdcryans sign theses Archives ! :fireworks: 
https://archive.apache.org/dist/hbase/KEYS

**Comment by davidonlaptop** [comment]
build success

@mikefaille : yeah, he's one of the main [contrib](https://github.com/apache/hbase/graphs/contributors)
